In [ ]:
# pip install numpy
import numpy as np

creating a numpy array

In [ ]:
x = [1, 2, 3, 4, 5]
nx = np.array(x)

In [ ]:
nx.ndim

In [ ]:
y = [[1,2,3], [4,5,6]]
ny = np.array(y)

In [ ]:
ny.ndim

In [ ]:
print(nx)
print(ny)

In [ ]:
nz = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
nz.ndim

In [ ]:
nx.shape

In [ ]:
ny.shape

In [ ]:
nz.shape

In [ ]:
y = np.linspace(0, 100, 50,)
print(y)

In [ ]:
a = np.random.rand(6)
print(a)

In [ ]:
b = np.random.rand(3, 3)
print(b)

In [ ]:
c = np.random.randint(0, 101, (3, 3))
print(c)

In [ ]:
d = np.random.choice(['❌','⭕'], (3,3))
print(d)

In [ ]:
o = np.ones((3,3), dtype=int)
print(o)

In [ ]:
e = np.eye(6, dtype=int)
print(e)

In [ ]:
np.diag(nx)

In [ ]:
c.transpose()

In [ ]:
print(c)
print()
print(c.T)

In [ ]:
c.size # number of elements

In [ ]:
c.dtype

In [81]:
x = np.array([[6,9],[6,9]])
y = np.array([[3,2],[1,3]])

In [83]:
print(x + y)

[[ 9 11]
 [ 7 12]]


In [84]:
x + 5

array([[11, 14],
       [11, 14]])

In [85]:
x.dot(y)

array([[27, 39],
       [27, 39]])

In [86]:
x * y

array([[18, 18],
       [ 6, 27]])

In [87]:
np.cross(x, y)

array([-15,   9])

In [89]:
np.sin(x)

array([[-0.2794155 ,  0.41211849],
       [-0.2794155 ,  0.41211849]])

In [93]:
y.argmin()

2

In [92]:
y

array([[3, 2],
       [1, 3]])

In [98]:
r = np.random.randint(-101, 101, (5,5))
r

array([[-84,  -7,  36,   4, -12],
       [ 17,  71,  59, -48, -59],
       [-42, -88,  -6,  93,  69],
       [ 46,  78,  57,  42, -73],
       [-87, -75, -28, -96,  58]])

In [99]:
r.max() , r.min()

(93, -96)

In [102]:
print(r.sum(), r.mean(), r.std(), r.var(), r.prod())

-75 -3.0 60.32777138267251 3639.44 -268435456
